### PR TITLE
refactor: Use the locally installed version of React in the demo page…

### PR DESCRIPTION
**Pull request by aaronkaka**
… rather than relying on a third-party CDN.

### CODE REVIEW

**Comment by StommePoes** [comment]
I like this.

**Comment by wyseguyonline** [comment]
lgtm

**Comment by umahaea** [comment]
let me run regression real quick n update here.

**Comment by umahaea** [comment]
Regression good:
Desktop: https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/167394712
Mobile: https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/167395919

**Pull request merged**
